encoding: utf-8
lang: en-AU
title: "Scott Gardner"
url: "https://sgardner.io"
repo: "https://github.com/Elmepo/elmepo.github.io"

sass:
  load_paths:
    - _sass
  # style: compressed

permalink: /:categories/:title
# permalink: /:title
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
      start_line: 1

plugins:
  - jekyll-feed
